config/routes.rb
Rails.application.routes.draw do
  root "buildings#index"
  get '/buildings/:building_id/apartaments', to:'apartaments#indexBuilding', as: 'apartamentBuildings' 
  resources :buildings 
  resources :apartaments
end

app/models/apartament.rb
class Apartament < ApplicationRecord
  belongs_to :building
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
    has_many :apartaments
end

app/controllers/apartaments_controller.rb
class ApartamentsController < ApplicationController
    def index
        @apartaments = Apartament.all
    end

    def indexBuilding
        @apartaments = Apartament.where(building_id:params[:building_id])
        @building = Building.find(params[:building_id])
    end
    
    def new
        @apartament = Apartament.new
        @buildings = Building.all
    end

    def create
        @buildings = Building.all
        @apartament = Apartament.new(apartament_params)
        if @apartament.save
            redirect_to apartaments_path
        else
            render :new
        end
    end

    def show
        @apartament = Apartament.find(params[:id])
    end
    
    

    private
        def apartament_params
            params.require(:apartament).permit(:number,:building_id)            
        end
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
    def index
        @buildings = Building.all        
    end

    def new
        @building = Building.new
    end

    def create
        @building = Building.create(buildings_params)
        if @building.save
            redirect_to @building
        else
            render :new
        end     
    end

    def show
        @building = Building.find(params[:id])
    end
    
    
    private
        def buildings_params
            params.require(:building).permit(:name,:address,:city)
        end
        
    
end

app/helpers/apartaments_helper.rb
module ApartamentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/apartaments/index.html.erb
<h1 class="my-3"> Listado de Departamentos</h1>

<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
        <th scope="col">Numero</th>
        <th scope="col">Edificio</th>
        <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <%@apartaments.each do |apartament|%>
    <tr>
        <td><%=apartament.number%></td>
        <td><%=apartament.building.name%></td>
        <td><%=button_to 'Ver detalle', apartament_path(apartament), class:"btn btn-warning text-dark", method: :get%></td>    
    </tr>
    <%end%>
  </tbody>
</table>

<%=button_to 'Agregar departamento', new_apartament_path, class:"btn btn-success my-3", method: :get%>

<%= button_to 'Volver', buildings_path, class:"btn btn-success", method: :get %>

app/views/apartaments/indexBuilding.html.erb
<h1 class="my-4">Departamentos en el edificio "<%=@building.name%>"</h1>
<p>El edificio tiene los siguientes departamentos:</p>
<ul>
    <%@apartaments.each do |apartament|%>
        <li><%=apartament.number%></li>
    <%end%>
</ul>

<%= link_to  'Volver',buildings_path, class:'btn btn-warning text-dark'%>

app/views/apartaments/new.html.erb
<h1 class="my-3"> Nuevo departamento </h1>
<%=form_with(model: [@building, @apartament], local: true) do |form|%>
    <div class="form">
        <div class="my-3">
            <%= form.label :number, 'Numero de apartamento', class:"form-label"%>
            <%= form.number_field :number , class:"form-control"%>
        </div>
        <div class="my-3">
            <%= form.label :building, 'Edificio', class:"form-label"%>
            <%# <%= form.number_field :building_id , class:"form-control"%>
            <% cities_array = Building.all.map { |building| [building.name, building.id] } %>
            <%= form.select :building_id, options_for_select(cities_array) %>

        </div>
        <div class="text-center">
            <%=form.submit 'Agregar Departamento', class:'btn btn-warning text-dark'%>
            <%= link_to 'Volver', apartaments_path, class:'btn btn-success' %>
        </div>
    </div>    
<% end %>    

app/views/apartaments/show.html.erb
<h1 class="my-3">Apartamento <%= @apartament.number %></h1>
<p><strong>Edificio :</strong> "<%= @apartament.building.name %>"</p> 
<p><strong>Ciudad: </strong><%= @apartament.building.city %></p> 
<p><strong>Direccion : </strong> <%= @apartament.building.address %></p>

<%= button_to 'volver', apartaments_path, method: :get, class:"btn btn-warning text-dark" %>

app/views/buildings/index.html.erb
<h1 class="my-3"> Listado de Edificios</h1>

<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Address</th>
        <th scope="col">City</th>
        <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <%@buildings.each do |building|%>
    <tr>
        <td><%=building.name%></td>
        <td><%=building.address%></td>
        <td><%=building.city%></td>
        <td><%= button_to 'Apartamentos', apartamentBuildings_path(building), method: :get, class:"btn btn-sm bg-warning text-dark"%></td>
        
    </tr>
    <%end%>
  </tbody>
</table>

<%=button_to 'Agregar edificio', new_building_path, class:"btn btn-success", method: :get%>
<%= link_to 'Ver listado Apartamentos', apartaments_path, class:"btn btn-warning text-dark" %>

app/views/buildings/new.html.erb
<h1 class="text-center my-4"> Nuevo Edificio</h1>

<%=form_with model:@building do |form|%>
    <div class="form">
        <div class="my-3">
            <%= form.label :name, 'Edificio', class:"form-label"%>
            <%= form.text_field :name , class:"form-control"%>
        </div>
        <div class="my-3">
            <%= form.label :city, 'Ciudad', class:"form-label"%>
            <%= form.text_field :city, class:"form-control"%>
        </div>
        <div class="my-3">
            <%= form.label :address, 'Direccion', class:"form-label"%>
            <%= form.text_field :address, class:"form-control"%>
        </div>
        <div class="text-center">
            <%=button_to 'Agregar nuevo edificio', buildings_path(@building), class:"btn btn-success" %>
            <%= link_to 'Volver', buildings_path, class:'btn btn-warning text-dark' %>
        </div>

    </div>    
<% end %>


    

app/views/buildings/show.html.erb
<h1 class="text-center my-3">Edificio "<%=@building.name%>"</h1>
<p><strong>Ciudad:</strong> <%= @building.city %></p>
<p><strong>Direccion:</strong> <%= @building.address %></p>

<div class="text-center">
    <%= button_to 'volver', buildings_path, method: :get, class:"btn btn-success" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExamenBuildings</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>Buildings</title>
  </head>

  <body class="container">
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>